services:
  web:
    build:
      context: .
    ports:
      - 5173:5173
    volumes:
      - .:/app   # Mount the source code
      - /usr/src/app/node_modules  # Keep node_modules intact in the container
